--- #YAML:1.0
name:                Devel-Cycle
version:             1.11
abstract:            Find memory cycles in objects
license:             ~
author:              
    - Lincoln Stein <lstein@cshl.edu>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Scalar::Util:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
